spring:
  application:
    name: inventory-service
  mongodb:
    uri: mongodb://localhost:27017/${DATABASE_NAME}
server:
  port: 8085

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true

